# Generated by Django 2.2.12 on 2022-08-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220823_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djelatnik',
            old_name='mail',
            new_name='email',
        ),
    ]
