# Generated by Django 2.2.12 on 2022-08-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220823_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djelatnik',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
